CREATE DATABASE PROFILE;
USE PROFILE;
CREATE TABLE USER(
	SLNO INT NOT NULL AUTO_INCREMENT UNIQUE KEY,
	FULLNAME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(30) PRIMARY KEY,
	USERNAME VARCHAR(30) NOT NULL UNIQUE KEY,
	PASSWORD VARCHAR(255) NOT NULL
);